package v1

/**
    AUTOGENERATED. Please, do not edit.
**/

import (
	"net/http"
)

/* Components schemas */

type ErrorSchema struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

type PetSchema struct {
	Id   int64   `json:"id"`
	Name string  `json:"name"`
	Tag  *string `json:"tag"`
}

type PetsSchema []PetSchema

/* Components responses */

/* Parameters */

type ListPetsParams struct {
	Limit *int32
}

type CreatePetsParams struct {
}

type ShowPetByIdParams struct {
	PetId string
}

/* Requests bodies */

/* Response objects */

/* Responses */

type ListPetsResponse struct {
	Code        int
	Http200     PetsSchema
	HttpDefault *ErrorSchema
}

type CreatePetsResponse struct {
	Code int

	HttpDefault *ErrorSchema
}

type ShowPetByIdResponse struct {
	Code        int
	Http200     *PetSchema
	HttpDefault *ErrorSchema
}

type Controller interface {
	ListPets(params *ListPetsParams, req *http.Request, res http.ResponseWriter) ListPetsResponse
	CreatePets(params *CreatePetsParams, req *http.Request, res http.ResponseWriter) CreatePetsResponse
	ShowPetById(params *ShowPetByIdParams, req *http.Request, res http.ResponseWriter) ShowPetByIdResponse
}
